id = "cyberzed"
name = "CyberZed"
description = "An utility extension based on the concept of gchq.github.io"
version = "0.1.0"
schema_version = 1
authors = ["akiidjk <akiidjk@proton.me>"]
repository = "https://github.com/akiidjk/cyberzed"
tags = ["utility", "encryption", "encoding"]

[slash_commands.echo]
description = "echoes the provided input"
requires_argument = true

[slash_commands.pick-one]
description = "pick one of three options"
requires_argument = true

[slash_commands.base64]
description = "Base64 encode/decode"
requires_argument = true

[slash_commands.hex]
description = "Hex encode/decode"
requires_argument = true

[slash_commands.md5]
description = "MD5 hash"
requires_argument = true

[slash_commands.sha]
description = "SHA256,SHA512,SHA384 functions"
requires_argument = true

[slash_commands.url]
description = "URL encode/decode"
requires_argument = true

[slash_commands.uuid]
description = "UUIDv4 generator"
requires_argument = true

[slash_commands.xor]
description = "XOR"
requires_argument = true
