id = "cyberzed"
name = "CyberZed"
description = "An utility extension based on the concept of gchq.github.io."
version = "0.1.0"
schema_version = 1
authors = ["akiidjk <akiidjk@proton.me>"]
repository = "https://github.com/akiidjk/cyberzed"

[cyberzed.echo]
description = "echoes the provided input"
requires_argument = true

[cyberzed.pick-one]
description = "pick one of three options"
requires_argument = true
